const REQUEST_URL = 'https://norma.nomoreparties.space/api' as const;
const GET_USER = 'GET_USER' as const;
const GET_USER_SUCCESS = 'GET_USER_SUCCESS' as const;
const GET_USER_FAILED = 'GET_USER_FAILED' as const;
const SET_USER = 'SET_USER' as const;
const REGISTER_USER = 'REGISTER_USER' as const;
const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS' as const;
const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED' as const;
const AUTHORIZE_USER = 'AUTHORIZE_USER' as const;
const AUTHORIZE_USER_SUCCESS = 'AUTHORIZE_USER_SUCCESS' as const;
const AUTHORIZE_USER_FAILED = 'AUTHORIZE_USER_FAILED' as const;
const REFRESH_TOKEN = 'REFRESH_TOKEN' as const;
const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS' as const;
const REFRESH_TOKEN_FAILED = 'REFRESH_TOKEN_FAILED' as const;
const LOGOUT = 'LOGOUT' as const;
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS' as const;
const LOGOUT_FAILED = 'LOGOUT_FAILED' as const;
const SET_PASSWORD_RESET = 'SET_PASSWORD_RESET' as const;

export {
    REQUEST_URL,
    GET_USER,
    GET_USER_SUCCESS,
    GET_USER_FAILED,
    SET_USER,
    REGISTER_USER,
    REGISTER_USER_SUCCESS,
    REGISTER_USER_FAILED,
    AUTHORIZE_USER,
    AUTHORIZE_USER_SUCCESS,
    AUTHORIZE_USER_FAILED,
    REFRESH_TOKEN,
    REFRESH_TOKEN_SUCCESS,
    REFRESH_TOKEN_FAILED,
    LOGOUT,
    LOGOUT_SUCCESS,
    LOGOUT_FAILED,
    SET_PASSWORD_RESET,
};
