const REQUEST_URL = 'https://norma.nomoreparties.space/api' as const;
const GET_USER = 'GET_USER' as const;
const GET_USER_SUCCESS = 'GET_USER_SUCCESS' as const;
const GET_USER_FAILED = 'GET_USER_FAILED' as const;
const SET_USER = 'SET_USER' as const;
const REGISTER_USER = 'REGISTER_USER' as const;
const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS' as const;
const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED' as const;
const AUTHORIZE_USER = 'AUTHORIZE_USER' as const;
const AUTHORIZE_USER_SUCCESS = 'AUTHORIZE_USER_SUCCESS' as const;
const AUTHORIZE_USER_FAILED = 'AUTHORIZE_USER_FAILED' as const;
const REFRESH_TOKEN = 'REFRESH_TOKEN' as const;
const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS' as const;
const REFRESH_TOKEN_FAILED = 'REFRESH_TOKEN_FAILED' as const;
const LOGOUT = 'LOGOUT' as const;
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS' as const;
const LOGOUT_FAILED = 'LOGOUT_FAILED' as const;
const SET_PASSWORD_RESET = 'SET_PASSWORD_RESET' as const;
const GET_INGREDIENTS = 'GET_INGREDIENTS' as const;
const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS' as const;
const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED' as const;
const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB' as const;
const INCREASE_INGREDIENT_COUNT = 'INCREASE_INGREDIENT_COUNT' as const;
const DECREASE_INGREDIENT_COUNT = 'DECREASE_INGREDIENT_COUNT' as const;
const ADD_INGREDIENT = 'ADD_INGREDIENT' as const;
const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT' as const;
const SET_TOTAL = 'SET_TOTAL' as const;
const SET_INGREDIENT_INDEX = 'SET_INGREDIENT_INDEX' as const;
const SET_INGREDIENTS_IDS = 'SET_INGREDIENTS_IDS' as const;
const MOVE_CARD = 'MOVE_CARD' as const;
const SET_INGREDIENT_DETAILS = 'SET_INGREDIENT_DETAILS' as const;
const REMOVE_INGREDIENT_DETAILS = 'REMOVE_INGREDIENT_DETAILS' as const;

export {
    REQUEST_URL,
    GET_USER,
    GET_USER_SUCCESS,
    GET_USER_FAILED,
    SET_USER,
    REGISTER_USER,
    REGISTER_USER_SUCCESS,
    REGISTER_USER_FAILED,
    AUTHORIZE_USER,
    AUTHORIZE_USER_SUCCESS,
    AUTHORIZE_USER_FAILED,
    REFRESH_TOKEN,
    REFRESH_TOKEN_SUCCESS,
    REFRESH_TOKEN_FAILED,
    LOGOUT,
    LOGOUT_SUCCESS,
    LOGOUT_FAILED,
    SET_PASSWORD_RESET,
    GET_INGREDIENTS,
    GET_INGREDIENTS_SUCCESS,
    GET_INGREDIENTS_FAILED,
    SET_ACTIVE_TAB,
    INCREASE_INGREDIENT_COUNT,
    DECREASE_INGREDIENT_COUNT,
    ADD_INGREDIENT,
    REMOVE_INGREDIENT,
    SET_TOTAL,
    SET_INGREDIENT_INDEX,
    SET_INGREDIENTS_IDS,
    MOVE_CARD,
    SET_INGREDIENT_DETAILS,
    REMOVE_INGREDIENT_DETAILS,
};
