export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_TOTAL = 'SET_TOTAL';
export const SET_INGREDIENT_INDEX = 'SET_INGREDIENT_INDEX';
export const SET_INGREDIENTS_IDS = 'SET_INGREDIENTS_IDS';
export const MOVE_CARD = 'MOVE_CARD';